.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. igocoin_qt test_igocoin_qt
clean: FORCE
	$(MAKE) -C .. igocoin_qt_clean test_igocoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_igocoin_qt_check
igocoin-qt igocoin-qt.exe: FORCE
	 $(MAKE) -C .. igocoin_qt
