description "Igocoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env IGOCOIND_BIN="/usr/bin/igocoind"
env IGOCOIND_USER="igocoin"
env IGOCOIND_GROUP="igocoin"
env IGOCOIND_PIDDIR="/var/run/igocoind"
# upstart can't handle variables constructed with other variables
env IGOCOIND_PIDFILE="/var/run/igocoind/igocoind.pid"
env IGOCOIND_CONFIGFILE="/etc/igocoin/igocoin.conf"
env IGOCOIND_DATADIR="/var/lib/igocoind"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # igocoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$IGOCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run igocoind."
        echo "The setting must appear in $IGOCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Igocoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$IGOCOIND_PIDDIR"
    chmod 0755 "$IGOCOIND_PIDDIR"
    chown $IGOCOIND_USER:$IGOCOIND_GROUP "$IGOCOIND_PIDDIR"
    chown $IGOCOIND_USER:$IGOCOIND_GROUP "$IGOCOIND_CONFIGFILE"
    chmod 0660 "$IGOCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$IGOCOIND_PIDFILE" \
    --chuid $IGOCOIND_USER:$IGOCOIND_GROUP \
    --exec "$IGOCOIND_BIN" \
    -- \
    -pid="$IGOCOIND_PIDFILE" \
    -conf="$IGOCOIND_CONFIGFILE" \
    -datadir="$IGOCOIND_DATADIR" \
    -disablewallet \
    -daemon

